"use client";
export const speciesList = {
  data: [
    {
      name: "BEE",
      image: "webp/Btn_BEE.webp",
      intro: "video/species/Sc_Bee.mp4",
      bright: "video/species/RB_Bee.mp4",
      dark: "video/species/EA_Bee.mp4",
      pledge_line: "I will feed bees and other pollinators.",
      pledge_link: "https://www.wildlifetrusts.org/actions/best-plants-bees-and-pollinators",
    },
    {
      name: "BEETLE",
      image: "webp/Btn_BEETLE.webp",
      intro: "video/species/Sc_Beetle.mp4",
      bright: "video/species/RB_Beetle.mp4",
      dark: "video/species/EA_Beetle.mp4",
      pledge_line: "I will buy food with the LEAF mark or buy organic.",
      pledge_link: "https://leaf.eco/about-leaf/what-we-do",
    },
    {
      name: "DOG",
      image: "webp/Btn_DOG.webp",
      intro: "video/species/Sc_Dog.mp4",
      bright: "video/species/RB_Dog.mp4",
      dark: "video/species/EA_dog.mp4",
      pledge_line: "I will pick up litter on all my walks.",
      pledge_link: "https://www.wildlifetrusts.org/actions/do-litter-pick-or-beach-clean",
    },

    {
      name: "GRASS",
      image: "webp/Btn_GRASS.webp",
      intro: "video/species/Sc_Grass.mp4",
      bright: "video/species/RB_Grass.mp4",
      dark: "video/species/EA_Grass.mp4",
      pledge_line: "I will scatter wildflower seeds on local grass patches.",
      pledge_link: "https://www.plantlife.org.uk/learning-resource/managing-road-verges-and-greenspaces/#resources",
    },
    {
      name: "HERON",
      image: "webp/Btn_HERON.webp",
      intro: "video/species/Sc_Heron.mp4",
      bright: "video/species/RB_heron.mp4",
      dark: "video/species/EA_Heron.mp4",
      pledge_line: "I will ask my MP how they are keeping our rivers clean.",
      pledge_link: "https://members.parliament.uk/member/4639/contact",
    },
    {
      name: "TREE",
      image: "webp/Btn_TREE.webp",
      intro: "video/species/Sc_Tree.mp4",
      bright: "video/species/RB_Tree.mp4",
      dark: "video/species/EA_Tree.mp4",
      pledge_line: "I will informally adopt and care for a local tree.",
      pledge_link: "https://www.observatree.org.uk/",
    },
    {
      name: "WHEAT",
      image: "webp/Btn_WHEAT.webp",
      intro: "video/species/Sc_Wheat.mp4",
      bright: "video/species/RB_wheat.mp4",
      dark: "video/species/EA_Wheat.mp4",
      pledge_line: "I will collect and use my rainwater.",
      pledge_link: "https://www.hertswildlifetrust.org.uk/actions/how-install-water-butt?gad_source=1&gclid=Cj0KCQiA84CvBhCaARIsAMkAvkJYngajMW7_hwa3hDA80cv0QJqrCwdU6VDw0NPF5GXFh2pKynON7WYaAo6HEALw_wcB",
    },
  ],
};
